"""
Regenerates variant_registry.json by scanning the font's own glyph inventory
for every "<name>.altN" glyph and grouping it by its base - so adding a new
hand-drawn alt glyph to the font, then re-running this script, is all that's
needed to register it (instead of hand-editing variant_registry.json, which
is what this file used to be).

Detection: any glyph name matching "<base>-tutg.altN" (or a bare "<base>-tutg.alt"
with no digit, e.g. lVocalicMatra-tutg.alt - a real naming inconsistency already
in the font, treated as index "1" the same way the hand-maintained file already
did) where "<base>-tutg" is itself a real glyph. Routed into one of two
sections by what the base actually is:

  - Single glyph (registry's top-level entries): base is classified as a
    "consonant", "vowel_independent", "vowel_sign", or "special_mark" (repha) -
    i.e. one real Unicode character with its own alt presentation forms.
  - Two-consonant conjunct ligature (registry["_conjunct_variants"]): base is
    "<first>_<second>-tutg" where both "<first>-tutg" and "<second>-tutg" are
    real, classified consonants - a real conjunct ligature glyph with its own
    stylistic alternate(s).

Anything else with an ".altN" sibling (compound consonant+vowel-sign ligatures
like ka_uMatra-tutg.alt, 3+ consonant conjuncts like ka_sa_sa-tutg.alt1, or a
base that turns out not to be a real glyph at all - a few genuine typos/
internal-tool artifacts already in the font, e.g. "_smart.vamatra-tutg.alt1")
is reported instead of guessed at, in VARIANT_REGISTRY_TODO.md - same
principle as every other gap in this project's GSUB tooling. Confirmed via a
2026-07 audit that every one of the current file's existing entries (57
single-glyph, 18 conjunct-ligature) round-trips through this script unchanged;
the "unclassified" list is new territory (mostly consonant+vowel-sign-ligature
alternates) this registry has never covered, not a regression.
"""
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))

with open(os.path.join(HERE, "glyph_svg_data.json"), encoding="utf-8") as f:
    glyphs = json.load(f)
with open(os.path.join(HERE, "glyph_classification.json"), encoding="utf-8") as f:
    classification = json.load(f)

consonant_names = set(classification.get("consonant", []))
vowel_independent_names = set(classification.get("vowel_independent", []))
vowel_sign_names = set(classification.get("vowel_sign", []))
special_mark_names = set(classification.get("special_mark", []))
single_glyph_bases = consonant_names | vowel_independent_names | vowel_sign_names | special_mark_names

# Bare ".alt" (no digit) is a real, existing naming inconsistency in this font
# (lVocalicMatra-tutg.alt, plus every "<cons>_lVocalicMatra-tutg.alt" compound)
# - treated as index "1", matching how the hand-maintained file already had it.
ALT_RE = re.compile(r"^(?P<base>.+-tutg)\.alt(?P<idx>\d*)$")

single_glyph_variants = {}  # base_name -> {index_str: alt_name}
conjunct_variants = {}      # first_name -> {second_name: {index_str: alt_name}}
compound_variants = {}      # cons_name -> {vowel_sign_root_name: {index_str: alt_name}}
skipped_no_base = []        # alt exists but "<base>-tutg" isn't a real glyph
skipped_unclassified = []   # base is a real glyph but not a category this registry handles

for name in sorted(glyphs):
    m = ALT_RE.match(name)
    if not m:
        continue
    base = m.group("base")
    idx = m.group("idx") or "1"
    if base not in glyphs:
        skipped_no_base.append(name)
        continue
    if base in single_glyph_bases:
        single_glyph_variants.setdefault(base, {})[idx] = name
        continue
    core = base[: -len("-tutg")]
    parts = core.split("_")
    if len(parts) == 2 and f"{parts[0]}-tutg" in consonant_names and f"{parts[1]}-tutg" in consonant_names:
        first_name, second_name = f"{parts[0]}-tutg", f"{parts[1]}-tutg"
        conjunct_variants.setdefault(first_name, {}).setdefault(second_name, {})[idx] = name
        continue
    # Prototype (2026-07-21): consonant + vowel-sign-root compound ligature
    # (e.g. ka_uMatra-tutg.alt1) - mechanically identical to the conjunct
    # case as far as GSUB is concerned (TutgConjunctVariantSelect just
    # matches "ligature glyph + VSn -> alt glyph", it doesn't care whether
    # the ligature is two consonants or a consonant+its own vowel sign), so
    # routed the same way and merged into the same lookup by
    # generate_akhn_feature.py - see its own comment for how.
    if len(parts) == 2 and f"{parts[0]}-tutg" in consonant_names and f"{parts[1]}-tutg" in vowel_sign_names:
        cons_name, vowel_root_name = f"{parts[0]}-tutg", f"{parts[1]}-tutg"
        compound_variants.setdefault(cons_name, {}).setdefault(vowel_root_name, {})[idx] = name
        continue
    skipped_unclassified.append(name)

registry = {
    "_readme": (
        "Auto-generated by generate_variant_registry.py (2026-07-21) - re-run "
        "it after adding a new '<name>-tutg.altN' glyph to the font instead of "
        "hand-editing this file; it will pick up the new variant automatically. "
        "Registry for selecting stylistic-alternate glyphs via Unicode "
        "Variation Selectors (VS1-VS6 for this layer - U+FE00-U+FE05) instead "
        "of OpenType stylistic-set features (ssXX). Consumed by "
        "generate_akhn_feature.py's TutgVariantSelect (akhn's first lookup): "
        "\"sub bha-tutg vs1-tutg by bha-tutg.alt1;\" and so on for every entry "
        "below - typing <base character><VSn> resolves to the glyph listed "
        "under key \"N\" here. Typing the base character alone (no selector) "
        "still resolves to its normal default glyph. Index \"1\" = VS1 "
        "(U+FE00), \"2\" = VS2 (U+FE01), etc. - built from every single-"
        "codepoint glyph (consonant/independent vowel/vowel sign/special mark) "
        "that has one or more '.altN' siblings in the font. This is a "
        "private/font-specific convention, not a Unicode-registered "
        "Ideographic Variation Sequence - only this font (and any tooling "
        "that reads this registry) knows what these particular base+selector "
        "pairs mean."
    ),
}
for base, variants in sorted(single_glyph_variants.items()):
    registry[base] = dict(sorted(variants.items(), key=lambda kv: int(kv[0])))

registry["_conjunct_variants_readme"] = (
    "Auto-generated alongside the section above - see generate_variant_registry.py. "
    "Selecting among alternate LIGATURE forms (e.g. ca_ca-tutg vs ca_ca-tutg.alt1) "
    "for specific two-consonant subjoining conjuncts. Mechanism (generate_akhn_feature.py's "
    "TutgConjunctVariantSelect, the LAST lookup in feature akhn): by the time this "
    "lookup runs, TutgAkhand has already collapsed e.g. 'ca-tutg conjoiner-tutg "
    "ca-tutg' into the single glyph ca_ca-tutg, so this is just a plain 2-glyph "
    "substitution keyed on the ligature's own output name - 'sub ca_ca-tutg "
    "vs11-tutg by ca_ca-tutg.alt1;' - same principle blwf's per-ligature rules "
    "already rely on (match the ligature's OUTPUT name, not its raw input "
    "sequence). Indices here are offset by +10 (index \"1\" -> VS11, \"2\" -> "
    "VS12, ...) to keep this layer's selector range visually distinct from the "
    "base-glyph variant registry above (VS1-VS6) and the subjoiner mechanism "
    "(VS1 on the conjoiner) - though nothing stops index reuse across layers "
    "in practice, since GSUB always disambiguates by the full starting glyph, "
    "not the selector alone. Scoped to plain two-consonant conjuncts only - "
    "3+-consonant conjuncts (e.g. ka_sa_sa-tutg) are picked up by this "
    "script's alt-glyph scan but deliberately left out of this section and "
    "reported in VARIANT_REGISTRY_TODO.md instead. Consonant+vowel-sign-root "
    "compound ligatures (e.g. ka_uMatra-tutg) get the identical mechanism but "
    "live in their own registry[\"_compound_variants\"] section below, since "
    "semantically they're a different thing (one consonant's own vowel sign, "
    "not two consonants) even though the GSUB rule shape is the same."
)
conjunct_out = {}
for first_name, seconds in sorted(conjunct_variants.items()):
    conjunct_out[first_name] = {
        second_name: dict(sorted(variants.items(), key=lambda kv: int(kv[0])))
        for second_name, variants in sorted(seconds.items())
    }
registry["_conjunct_variants"] = conjunct_out

registry["_compound_variants_readme"] = (
    "PROTOTYPE (2026-07-21) - auto-generated alongside the sections above, see "
    "generate_variant_registry.py. Selecting among alternate LIGATURE forms for "
    "consonant + OWN vowel-sign compound ligatures (e.g. ka_uMatra-tutg vs "
    "ka_uMatra-tutg.alt1) - mechanically identical to _conjunct_variants above "
    "(TutgConjunctVariantSelect just matches \"ligature glyph + VSn -> alt "
    "glyph\", it doesn't care whether the ligature came from two consonants or "
    "one consonant + its own vowel sign), so generate_akhn_feature.py folds "
    "these into the exact same lookup, same +10 VS-index offset, rather than "
    "building a second lookup for what's really the same rule shape. Kept in "
    "a separate registry section from _conjunct_variants purely because the "
    "two are semantically different things worth being able to tell apart at "
    "a glance, not because the mechanism differs."
)
compound_out = {}
for cons_name, roots in sorted(compound_variants.items()):
    compound_out[cons_name] = {
        root_name: dict(sorted(variants.items(), key=lambda kv: int(kv[0])))
        for root_name, variants in sorted(roots.items())
    }
registry["_compound_variants"] = compound_out

conjunct_pair_count = sum(len(seconds) for seconds in conjunct_variants.values())
conjunct_entry_count = sum(len(variants) for seconds in conjunct_variants.values() for variants in seconds.values())
compound_pair_count = sum(len(roots) for roots in compound_variants.values())
compound_entry_count = sum(len(variants) for roots in compound_variants.values() for variants in roots.values())

out_path = os.path.join(HERE, "variant_registry.json")
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(registry, f, indent=2, ensure_ascii=False)
    f.write("\n")

# markdown report - written even when nothing is unclassified, so a re-run's
# "all clear" is an explicit, checkable fact rather than the mere absence of a file.
report_path = os.path.join(HERE, "VARIANT_REGISTRY_TODO.md")
with open(report_path, "w", encoding="utf-8") as f:
    f.write("# variant_registry.json coverage report\n\n")
    f.write(f"Generated by `generate_variant_registry.py` - {sum(len(v) for v in single_glyph_variants.values())} "
            f"single-glyph variant entries ({len(single_glyph_variants)} bases), "
            f"{conjunct_entry_count} conjunct-ligature variant entries "
            f"({conjunct_pair_count} pairs), {compound_entry_count} consonant+vowel-sign "
            f"compound-ligature variant entries ({compound_pair_count} pairs, prototype).\n\n")

    if skipped_unclassified:
        bases = sorted(set(n.rsplit(".alt", 1)[0] for n in skipped_unclassified))
        f.write(f"## {len(skipped_unclassified)} alt glyph(s) with a base this registry doesn't handle yet ({len(bases)} distinct bases)\n\n")
        f.write("Not consonant/vowel/vowel-sign/mark, not a plain two-consonant conjunct, and not a "
                "consonant+own-vowel-sign compound - mostly 3+-consonant conjuncts (e.g. "
                "`ka_sa_sa-tutg`). Neither `generate_akhn_feature.py` nor `generate_blwf_feature.py` "
                "currently has a mechanism wired up for these - listed here for a future decision, "
                "not included in variant_registry.json.\n\n")
        for base in bases:
            variants = sorted(n for n in skipped_unclassified if n.rsplit(".alt", 1)[0] == base)
            f.write(f"- `{base}`: {', '.join(variants)}\n")
        f.write("\n")
    else:
        f.write("**All clear** - every `.altN` glyph in the font is either a registered "
                "single-glyph or conjunct-ligature variant.\n\n")

    if skipped_no_base:
        f.write(f"## {len(skipped_no_base)} alt glyph(s) with no real base glyph at all\n\n")
        f.write("The glyph name implies a base (`<name>-tutg`) that doesn't actually exist in "
                "the font - likely a typo or an internal tool artifact, not a real variant.\n\n")
        for name in skipped_no_base:
            f.write(f"- `{name}`\n")
        f.write("\n")

print(f"Single-glyph variant bases: {len(single_glyph_variants)}")
print(f"Single-glyph variant entries: {sum(len(v) for v in single_glyph_variants.values())}")
print(f"Conjunct-ligature variant pairs: {conjunct_pair_count}")
print(f"Conjunct-ligature variant entries: {conjunct_entry_count}")
print(f"Compound (consonant+vowel-sign) variant pairs: {compound_pair_count}")
print(f"Compound (consonant+vowel-sign) variant entries: {compound_entry_count}")
print(f"Skipped - unclassified base: {len(skipped_unclassified)} (see {os.path.basename(report_path)})")
print(f"Skipped - no real base glyph: {len(skipped_no_base)} {skipped_no_base}")
print("Written to:", out_path)
print("Written to:", report_path)
