"""
Builds a ready-to-merge .fea file for the `blwf` (Below-base Forms) feature: for
every one of the 36 Tulu-Tigalari consonants, "conjoiner + consonant" substitutes
the *pair* for the consonant's below-base allograph (this font's "Adi Vottu" form,
see tulu-tigalari-shaping-model memory).

This MUST be a ligature-style substitution (both input glyphs consumed, one output
glyph: `sub conjoiner-tutg ka-tutg by ka-tutg.below;`), not a chaining-contextual
single substitution (`sub conjoiner-tutg ka-tutg' by ka-tutg.below;`). The latter
only replaces the marked glyph and leaves `conjoiner-tutg` itself sitting in the
glyph stream afterward - and conjoiner-tutg has real, visible dotted-circle-style
artwork drawn (the intended USE fallback appearance for an Invisible_Stacker that
never got consumed), so that bug renders as a dotted circle glaring out of every
below-base conjunct instead of a clean stack. Confirmed via uharfbuzz before/after:
the contextual form left `u113D0` (conjoiner) in the shaped glyph list; the
ligature form consumes it entirely.

Why this feature exists alongside `akhn` (generate_akhn_feature.py): `akhn` only
covers the 452 combinations that have a dedicated, hand-drawn ligature glyph
(e.g. ka_ka-tutg). Most of the 36*36 possible consonant pairs have no such glyph.
Per the standard Indic/USE feature-application order, `akhn` runs first and claims
whatever specific conjuncts it recognizes; any "conjoiner + consonant" sequence
`akhn` didn't touch reaches `blwf` unchanged, which then applies this generic
fallback - so every possible conjunct renders as *something* correctly shaped
(a below-base stack), not a default/unjoined pair, even without a bespoke ligature.

Below-base glyph naming is almost universally "{consonant}.below" (e.g.
ka-tutg -> ka-tutg.below), EXCEPT for RA: its below-base combining form is a
completely different glyph, "raMatra-tutg" (used as a component in ligatures like
ba_ra-tutg) - the same fact generate_akhn_feature.py's TOKEN_ALIASES already
relies on. BELOW_FORM_OVERRIDES documents that one exception explicitly rather
than assuming the ".below" suffix pattern always holds.

Any consonant that turns out to have NO below-base glyph at all (neither the
".below" suffix nor a listed override) is reported in BLWF_TODO.md instead of
silently skipped or guessed at - same principle as every other gap in this
project's GSUB tooling.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))

with open(os.path.join(HERE, "glyph_svg_data.json"), encoding="utf-8") as f:
    glyphs = json.load(f)
with open(os.path.join(HERE, "glyph_classification.json"), encoding="utf-8") as f:
    classification = json.load(f)


def cp_of(name):
    u = glyphs.get(name, {}).get("unicodes", [])
    return u[0] if u else None


def is_default_form(name):
    # no ".below"/".altN"/other suffix after "-tutg" - same filter
    # build_test_page_data.py uses to get the canonical 36-consonant list.
    return "-tutg" in name and "." not in name.partition("-tutg")[2]


consonants = [n for n in classification.get("consonant", []) if is_default_form(n) and cp_of(n) is not None]
consonants.sort(key=cp_of)

# RA's below-base combining form is a different glyph entirely, not "ra-tutg.below"
# (which doesn't exist) - see module docstring.
BELOW_FORM_OVERRIDES = {"ra-tutg": "raMatra-tutg"}

rules = []    # (consonant_name, below_name)
missing = []  # consonant_name
for name in consonants:
    below = BELOW_FORM_OVERRIDES.get(name, name + ".below")
    if below in glyphs:
        rules.append((name, below))
    else:
        missing.append(name)

out_path = os.path.join(HERE, "tutg_blwf.fea")
with open(out_path, "w", encoding="utf-8") as f:
    f.write("# Auto-generated by generate_blwf_feature.py - below-base form fallback for\n")
    f.write("# the Tulu-Tigalari (tutg) script: any \"conjoiner + consonant\" sequence that\n")
    f.write("# akhn's dedicated ligatures didn't already claim falls through to this generic\n")
    f.write("# below-base substitution. Review before merging into the real features.fea\n")
    f.write("# (which still has unrelated Latin kerning/numeral features and a dead\n")
    f.write("# Malayalam scaffold that should be removed separately).\n\n")

    f.write("languagesystem DFLT dflt;\n")
    f.write("languagesystem tutg dflt;\n\n")

    f.write("feature blwf {\n")
    f.write("    script tutg;\n")
    f.write("    lookup TutgBlwf {\n")
    for name, below in rules:
        f.write(f"        sub conjoiner-tutg {name} by {below};\n")
    f.write("    } TutgBlwf;\n")
    f.write("} blwf;\n")

    if missing:
        f.write("\n# --- No below-base glyph found for these consonants (see BLWF_TODO.md) ---\n")
        for name in missing:
            f.write(f"# {name}\n")

# markdown report - written even when nothing is missing, so a re-run's "all clear"
# is an explicit, checkable fact rather than the mere absence of a file.
report_path = os.path.join(HERE, "BLWF_TODO.md")
with open(report_path, "w", encoding="utf-8") as f:
    f.write("# blwf (Below-base Forms) coverage report\n\n")
    f.write(f"Generated by `generate_blwf_feature.py` against {len(consonants)} consonants.\n\n")
    if missing:
        f.write(f"## {len(missing)} consonant(s) with no below-base glyph\n\n")
        f.write("Neither a `{name}.below` glyph nor an entry in `BELOW_FORM_OVERRIDES` was found, so\n")
        f.write("`blwf` has no fallback rule for these - conjuncts ending in them will render\n")
        f.write("unjoined unless an `akhn` ligature already covers that specific pair.\n\n")
        for name in missing:
            f.write(f"- `{name}`\n")
    else:
        f.write("**All clear** - every one of the 36 consonants has a below-base glyph "
                "(35 via the `{name}.below` naming convention, RA via the `raMatra-tutg` "
                "override), so `blwf` has a fallback rule for every possible conjunct.\n")

print(f"Consonants checked: {len(consonants)}")
print(f"Rules written: {len(rules)}")
print(f"Missing below-base glyph: {len(missing)} {missing}")
print("Written to:", out_path)
print("Written to:", report_path)
