"""
Generates ANCHORS.md - a full reference of every GPOS anchor generate_anchors.py
writes: which glyphs get which anchor, and exactly which algorithm computed its
x/y. Read-only on the UFO (never calls font.save()) - re-derives the same
pools/overrides generate_anchors.py builds, from the same source files
(glyph_classification.json, variant_registry.json, the font's own glyph list),
so this always reflects the current rules rather than a hand-maintained summary
that can drift out of sync with the real generator.

    wsl python3 generate_anchor_doc.py
"""
import json
import os

import ufoLib2

HERE = os.path.dirname(os.path.abspath(__file__))
UFO_PATH = os.path.join(os.path.dirname(HERE), "Ikshu-Regular.ufo")
OUT_PATH = os.path.join(HERE, "ANCHORS.md")

font = ufoLib2.Font.open(UFO_PATH)
with open(os.path.join(HERE, "glyph_classification.json"), encoding="utf-8") as f:
    d = json.load(f)
with open(os.path.join(HERE, "variant_registry.json"), encoding="utf-8") as f:
    variant_registry = json.load(f)

# --- re-derive the exact same pools/overrides as generate_anchors.py ---

BELOW_AUTO_POP = [n for n in font.keys() if n.endswith(".below.auto")]


def _suffix_tags(name):
    _, _, suffix = name.partition("-tutg")
    return set(t for t in suffix.split(".") if t)


def _is_below_form(name):
    return "below" in _suffix_tags(name)


LIGATURE_BELOW_FORMS = [n for n in d["conjunct_ligature"] + d["vowel_sign_ligature"] if _is_below_form(n)]

TOP_POP = [n for n in d["consonant"] + d["conjunct_ligature"] + d["vowel_sign_ligature"] if not _is_below_form(n)]
BOTTOM_POP = d["consonant"] + d["consonant_below_base"] + d["conjunct_ligature"] + d["vowel_sign_ligature"] + BELOW_AUTO_POP

SPACING_VS_ROOTS = ("aaMatra-tutg", "iMatra-tutg", "iiMatra-tutg", "eeMatra-tutg",
                    "aiMatra-tutg", "ooMatra-tutg", "auMatra-tutg", "aulengthmark-tutg")
spacing_vs = [n for n in d["vowel_sign"] + d["special_mark"] if n in SPACING_VS_ROOTS]
TOPRIGHT_POP = [n for n in d["consonant"] + d["conjunct_ligature"] + d["vowel_sign_ligature"] + spacing_vs
                if not _is_below_form(n)]

BARE_YA_LIGATURES = {n for n in font.keys() if n.endswith("_ya-tutg")}
BARE_RA_LIGATURES = {n for n in font.keys() if n.endswith("_ra-tutg")}

BOTTOMRIGHT_POP = (
    d["consonant"] + d["consonant_below_base"] + LIGATURE_BELOW_FORMS + BELOW_AUTO_POP
    + list(BARE_YA_LIGATURES) + list(BARE_RA_LIGATURES) + ["raMatra-tutg"]
)

MARKS_TOP = ["repha-tutg", "repha-tutg.alt1", "svarita-tutg"]
MARKS_BOTTOM = ["anudatta-tutg", "germinationmark-tutg", "lVocalicMatra-tutg", "llVocalicMatra-tutg"]
MARKS_TOPRIGHT = ["virama-tutg"]
MARKS_BOTTOMRIGHT = ["uMatra-tutg", "uuMatra-tutg", "rVocalicMatra-tutg", "rrVocalicMatra-tutg"]
MARKS_BOTTOMRIGHT_MISSING_VARIANT = []
for _base_name in list(MARKS_BOTTOMRIGHT):
    for _variant_name in variant_registry.get(_base_name, {}).values():
        if _variant_name not in font:
            MARKS_BOTTOMRIGHT_MISSING_VARIANT.append((_base_name, _variant_name))
            continue
        MARKS_BOTTOMRIGHT.append(_variant_name)
for _below_name in ("uMatra-tutg.below", "uuMatra-tutg.below"):
    if _below_name in font:
        MARKS_BOTTOMRIGHT.append(_below_name)

MARKS_BOTTOMRIGHT_TOPMOST_OVERRIDE = {
    "uMatra-tutg", "uMatra-tutg.alt2", "uMatra-tutg.alt3", "uMatra-tutg.alt4",
    "uMatra-tutg.alt5", "uMatra-tutg.alt6", "uMatra-tutg.below",
    "uuMatra-tutg", "uuMatra-tutg.alt4", "uuMatra-tutg.below",
}

BOTTOMRIGHT_LOWEST_POINT_OVERRIDE = {
    n for n in font.keys()
    if n == "ya-tutg.below"
    or n.endswith("_ya-tutg.below") or n.endswith("_ya-tutg.below.auto")
    or n.endswith("_ra-tutg.below") or n.endswith("_ra-tutg.below.auto")
} | BARE_YA_LIGATURES | BARE_RA_LIGATURES


def anchor_val(gname, aname):
    g = font.get(gname)
    if g is None:
        return None
    a = next((a for a in g.anchors if a.name == aname), None)
    if a is None:
        return None
    return (round(a.x, 1), round(a.y, 1))


def fmt_list(names, limit=None):
    names = sorted(names)
    if limit is not None and len(names) > limit:
        shown = ", ".join(f"`{n}`" for n in names[:limit])
        return f"{shown}, ... ({len(names)} total)"
    return ", ".join(f"`{n}`" for n in names) if names else "*(none)*"


def table(rows, headers):
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    for row in rows:
        out.append("| " + " | ".join(str(c) for c in row) + " |")
    return "\n".join(out)


lines = []
lines.append("# Anchor Reference")
lines.append("")
lines.append("Auto-generated by `generate_anchor_doc.py` from the current UFO + "
             "`glyph_classification.json` + `variant_registry.json` - re-run after "
             "`generate_anchors.py` to keep this in sync. Documents every GPOS "
             "anchor pair `generate_anchors.py` writes: which glyphs get it and the "
             "exact algorithm used to compute its x/y.")
lines.append("")
lines.append("## Overview")
lines.append("")
lines.append(table(
    [
        ("`top` / `_top`", "Repha, Svarita"),
        ("`bottom` / `_bottom`", "Anudatta, Gemination mark, Vocalic-L, Vocalic-LL"),
        ("`topright` / `_topright`", "Virama (USE \"Bindu\" override behavior)"),
        ("`bottomright` / `_bottomright`", "Vowel Sign U/UU/Vocalic-R/Vocalic-RR (fallback mark-attachment path, "
         "used when no dedicated ligature glyph exists)"),
    ],
    ["Anchor pair", "Used for"],
))
lines.append("")
lines.append("All anchors are re-runnable/idempotent: `upsert_anchor()` updates an existing "
             "anchor of the same name in place rather than skipping or duplicating it, so "
             "re-running `generate_anchors.py` after a GAP constant or algorithm change "
             "retunes every affected glyph with no manual cleanup.")

# --- top / _top ---
lines.append("")
lines.append("## `top` / `_top`")
lines.append("")
lines.append("**Base algorithm (`base_pass`, x_from=\"center\", y_edge=\"max\"):** "
             f"x = bbox horizontal center, y = bbox `yMax` + `TOP_GAP` (50 units).")
lines.append("")
lines.append(f"**Base glyphs ({len(TOP_POP)} total)** - every consonant, plus every "
              "non-below-form conjunct/vowel-sign ligature (`d[\"consonant\"] + "
              "d[\"conjunct_ligature\"] + d[\"vowel_sign_ligature\"]`, below-forms excluded):")
lines.append("")
lines.append(fmt_list(d["consonant"]) + f" *(the 36 consonants + their {len(d['consonant']) - 36} registered `.altN` variants, {len(d['consonant'])} total)*")
lines.append("")
lines.append(f"Plus {len([n for n in TOP_POP if n not in d['consonant']])} non-below-form "
              "conjunct/vowel-sign ligatures (not listed individually - see "
              "`glyph_classification.json`'s `conjunct_ligature`/`vowel_sign_ligature`).")
lines.append("")
lines.append("**Mark algorithm (`mark_pass`, x_from=\"center\", y_edge=\"min\"):** "
             "x = bbox horizontal center, y = bbox `yMin` (no gap - sits exactly at the mark's own bottom edge).")
lines.append("")
lines.append(f"**Mark glyphs:** {fmt_list(MARKS_TOP)}")

# --- bottom / _bottom ---
lines.append("")
lines.append("## `bottom` / `_bottom`")
lines.append("")
lines.append("**Base algorithm (`base_pass`, x_from=\"center\", y_edge=\"min\"):** "
             "x = bbox horizontal center, y = bbox `yMin` - `BOTTOM_GAP` (50 units).")
lines.append("")
lines.append(f"**Base glyphs ({len(BOTTOM_POP)} total):** every consonant + `consonant_below_base` "
              "+ every conjunct/vowel-sign ligature (below-forms included here, unlike `top` - a "
              "below-form can itself be the base for further stacking) + every `*.below.auto` glyph.")
lines.append("")
lines.append(f"- Consonants ({len(d['consonant'])}, includes `.altN` variants): {fmt_list(d['consonant'], limit=15)}")
lines.append(f"- Consonant below-base forms ({len(d['consonant_below_base'])}): {fmt_list(d['consonant_below_base'], limit=15)}")
lines.append(f"- `*.below.auto` ligatures: {len(BELOW_AUTO_POP)} glyphs (auto-generated, see `generate_below_auto_glyphs.py`)")
lines.append("")
lines.append("**Special case - `raMatra-tutg`:** RA's own post-base \"Rakar\" combining form is "
              "classified as `vowel_sign_component` in `glyph_classification.json`, not "
              "`consonant`/`consonant_below_base`, so it falls through the pool above entirely - "
              "confirmed to have had **zero anchors at all** until 2026-07-22. Fixed with a "
              "dedicated one-off call using `find_lowest_point` (its true bottommost ink point) "
              "instead of the generic bbox-center-minus-gap formula, per project owner's explicit request:")
val = anchor_val("raMatra-tutg", "bottom")
lines.append("")
lines.append(f"- `raMatra-tutg` -> `bottom` = `{val}` (algorithm: `find_lowest_point` - true minimum-y outline point)")
lines.append("")
lines.append("**Mark algorithm (`mark_pass`, x_from=\"center\", y_edge=\"max\"):** "
             "x = bbox horizontal center, y = bbox `yMax` (sits exactly at the mark's own top edge).")
lines.append("")
lines.append(f"**Mark glyphs:** {fmt_list(MARKS_BOTTOM)}")

# --- topright / _topright ---
lines.append("")
lines.append("## `topright` / `_topright`")
lines.append("")
lines.append("**Base algorithm (`base_pass`, x_from=\"edge\", y_edge=\"max\"):** "
             "x = bbox `xMax`, y = bbox `yMax` + `TOPRIGHT_GAP` (50 units).")
lines.append("")
lines.append(f"**Base glyphs ({len(TOPRIGHT_POP)} total):** consonants + non-below-form "
              "conjunct/vowel-sign ligatures + the 8 spacing vowel signs "
              f"({', '.join(f'`{n}`' for n in SPACING_VS_ROOTS)}) that need Virama-as-Bindu support.")
lines.append("")
lines.append("**Mark algorithm (`mark_pass`, x_from=\"left\", y_edge=\"min\"):** "
             "x = bbox `xMin`, y = bbox `yMin`.")
lines.append("")
lines.append(f"**Mark glyphs:** {fmt_list(MARKS_TOPRIGHT)}")

# --- bottomright / _bottomright ---
lines.append("")
lines.append("## `bottomright` / `_bottomright`")
lines.append("")
lines.append("This is the most-iterated-on anchor pair in the font (fallback mark-attachment "
              "path for U/UU/Vocalic-R/Vocalic-RR when GSUB leaves no dedicated per-consonant "
              "ligature glyph to fall back on) and has three distinct algorithms depending on "
              "glyph shape.")
lines.append("")
lines.append("### Base side (`bottomright`)")
lines.append("")
lines.append(f"**Default algorithm (`find_ink_bottom_right`)** - not bbox-based: scans the "
              "glyph's actual outline (including through components) for the point that "
              "maximizes the blended score `(x-xMin)/width + (1-(y-yMin)/height)` - i.e. "
              "simultaneously furthest right AND furthest down - so the fallback vowel sign "
              "visually touches the consonant's ink instead of floating off an empty bbox corner.")
lines.append("")
lines.append(f"Applies to every glyph in `BOTTOMRIGHT_POP` ({len(BOTTOMRIGHT_POP)} total) "
              "*except* the override set below:")
lines.append(f"- Consonants ({len(d['consonant'])}, includes `.altN` variants): {fmt_list(d['consonant'])}")
lines.append(f"- Consonant below-base forms: {len(d['consonant_below_base'])} glyphs")
lines.append(f"- Ligature below-forms (hand-drawn `.below`): {len(LIGATURE_BELOW_FORMS)} glyphs")
lines.append(f"- `*.below.auto` ligatures: {len(BELOW_AUTO_POP)} glyphs")
lines.append(f"- `raMatra-tutg` (added 2026-07-22 - see `bottom` section above for why it needed "
              "anchors added at all; uses the *default* algorithm here, deliberately \"the same "
              "way as every other plain consonant\" per project owner's request, unlike its "
              "`bottom` anchor which needed the lowest-point override):")
val = anchor_val("raMatra-tutg", "bottomright")
lines.append(f"  - `raMatra-tutg` -> `bottomright` = `{val}`")
lines.append("")
lines.append(f"**Override algorithm (`find_lowest_point`, via `BOTTOMRIGHT_LOWEST_POINT_OVERRIDE`, "
              f"{len(BOTTOMRIGHT_LOWEST_POINT_OVERRIDE)} glyphs):** the true minimum-y outline "
              "point (x is whatever that point's own x happens to be), not the blended corner "
              "score. `_ya`/`_ra`-ending glyphs (bare or below-form) are all built with "
              "`ya-tutg`/`raMatra-tutg`'s own descending tail as a component, which extends much "
              "further down than right - the blended score picks a point on the side of the "
              "tail, well above the true bottom (confirmed 2026-07-21 against all 47 `_ya` "
              "below-forms, each off by 8-251 units from the true lowest point).")
lines.append("")
lines.append(f"- `ya-tutg.below` (exact name)")
lines.append(f"- Every `*_ya-tutg.below[.auto]` / `*_ra-tutg.below[.auto]` ligature below-form")
lines.append(f"- Every bare (non-below-form) `*_ya-tutg` / `*_ra-tutg` ligature (`BARE_YA_LIGATURES`/`BARE_RA_LIGATURES`)")
lines.append("")
lines.append(f"Full current list ({len(BOTTOMRIGHT_LOWEST_POINT_OVERRIDE)}): {fmt_list(BOTTOMRIGHT_LOWEST_POINT_OVERRIDE, limit=25)}")

lines.append("")
lines.append("### Mark side (`_bottomright`)")
lines.append("")
lines.append(f"**Default algorithm (`find_ink_top_right`)** - the mirror-image blended ink "
              "search: maximizes `(x-xMin)/width + (y-yMin)/height` - furthest right AND "
              "furthest **up**. This is where these marks visually begin (matching the base "
              "glyph's own furthest-right-furthest-down point, which is where they're meant to "
              "attach). An earlier leftmost-point approach was tried and rejected (2026-07-22): "
              "U/UU are round/circular enough that their true leftmost point sits at the "
              "vertical middle, nowhere near the visual start of the stroke.")
lines.append("")
lines.append(f"**Override algorithm (`find_topmost_point`, via `MARKS_BOTTOMRIGHT_TOPMOST_OVERRIDE`, "
              f"{len(MARKS_BOTTOMRIGHT_TOPMOST_OVERRIDE)} glyphs):** simply the glyph's own "
              "topmost outline point (max y), at that point's true x - not forced to bbox "
              "center, but for a round dot shape this naturally lands near the horizontal "
              "center anyway (it's the shape's own \"12 o'clock\", where quadrant 1 starts going "
              "clockwise). Confirmed by the project owner (2026-07-22) that these specific "
              "glyphs read as plain round dots, where the right-biased blended score was visibly "
              "wrong:")
lines.append("")
lines.append(f"{fmt_list(MARKS_BOTTOMRIGHT_TOPMOST_OVERRIDE)}")
lines.append("")
lines.append(f"**All `{len(MARKS_BOTTOMRIGHT)}` mark glyphs with current values:**")
lines.append("")
rows = []
for gname in sorted(MARKS_BOTTOMRIGHT):
    algo = "find_topmost_point" if gname in MARKS_BOTTOMRIGHT_TOPMOST_OVERRIDE else "find_ink_top_right"
    val = anchor_val(gname, "_bottomright")
    rows.append((f"`{gname}`", algo, val))
lines.append(table(rows, ["Glyph", "Algorithm", "_bottomright (x, y)"]))

if MARKS_BOTTOMRIGHT_MISSING_VARIANT:
    lines.append("")
    lines.append("**Registered but not real glyphs (skipped):** "
                  + ", ".join(f"`{b}` -> `{v}`" for b, v in MARKS_BOTTOMRIGHT_MISSING_VARIANT))

lines.append("")
lines.append("---")
lines.append("")
lines.append("## Source functions (in `generate_anchors.py`)")
lines.append("")
lines.append(table(
    [
        ("`base_pass(pop, name, gap, x_from, y_edge)`", "bbox edge +/- gap, x = center or edge"),
        ("`mark_pass(names, name, x_from, y_edge)`", "bbox edge, x = center/left/right, no gap"),
        ("`find_ink_bottom_right(glyph, font)`", "ink search, max((x-xMin)/w + (1-(y-yMin)/h)) - furthest right + furthest down"),
        ("`find_ink_top_right(glyph, font)`", "ink search, max((x-xMin)/w + (y-yMin)/h) - furthest right + furthest up"),
        ("`find_lowest_point(glyph, font)`", "ink search, true minimum-y outline point"),
        ("`find_topmost_point(glyph, font)`", "ink search, true maximum-y outline point"),
    ],
    ["Function", "Formula"],
))

with open(OUT_PATH, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")

print("Written to:", OUT_PATH)
print("No-bounds glyphs (bottomright/bottom pass would have skipped, if any need checking manually):")
print("  raMatra-tutg bottom:", anchor_val("raMatra-tutg", "bottom"))
print("  raMatra-tutg bottomright:", anchor_val("raMatra-tutg", "bottomright"))
